import { SceneConfig } from '../types/scene';

export const SCENES: SceneConfig[] = [
  {
    id: 'scene-01',
    index: 0,
    chapterNumber: '01',
    folderName: 'entry eye',
    frameCount: 300,
    title: 'THE LAIR AWAKENS',
    subtitle: 'Something ancient waits beneath the ruins.',
    eyebrow: 'CHAPTER I · THE VIGIL',
    colorAccent: '#10b981',
    vignetteStrength: 0.85,
    scrollWeight: 1.0,
    desktop: {
      objectPosition: 'center 48%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '580px',
    },
    mobile: {
      objectPosition: 'center 45%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '320px',
    },
  },
  {
    id: 'scene-02',
    index: 1,
    chapterNumber: '02',
    folderName: 'serpent_temple door opening',
    frameCount: 300,
    title: 'THE FORBIDDEN GATE',
    subtitle: 'The path below was never meant to be found.',
    eyebrow: 'CHAPTER II · THE THRESHOLD',
    colorAccent: '#059669',
    vignetteStrength: 0.75,
    scrollWeight: 1.2,
    desktop: {
      objectPosition: 'center 50%',
      scale: 1.0,
      textPosition: 'bottom-left',
      textMaxWidth: '520px',
    },
    mobile: {
      objectPosition: 'center 50%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '310px',
    },
  },
  {
    id: 'scene-03',
    index: 2,
    chapterNumber: '03',
    folderName: 'damyaan pathway',
    frameCount: 300,
    title: 'FOLLOW THE SERPENT',
    subtitle: 'Every path leads deeper into the subterranean abyss.',
    eyebrow: 'CHAPTER III · THE DESCENT',
    colorAccent: '#047857',
    vignetteStrength: 0.8,
    scrollWeight: 1.3,
    desktop: {
      objectPosition: 'center 52%',
      scale: 1.0,
      textPosition: 'bottom-left',
      textMaxWidth: '480px',
    },
    mobile: {
      objectPosition: 'center 50%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '300px',
    },
  },
  {
    id: 'scene-04',
    index: 3,
    chapterNumber: '04',
    folderName: 'damyaan entry',
    frameCount: 300,
    title: 'DAMYAAN',
    subtitle: 'THE SERPENT LORD',
    storyDetail: 'Ruler of shadow and primordial venom. His presence commands silence.',
    eyebrow: 'CHAPTER IV · THE CONFRONTATION',
    isHero: true,
    colorAccent: '#34d399',
    vignetteStrength: 0.65,
    scrollWeight: 1.8, // extra scroll budget for the hero reveal
    desktop: {
      objectPosition: 'center 38%', // protect face and hood
      scale: 1.02,
      textPosition: 'bottom-center',
      textMaxWidth: '640px',
    },
    mobile: {
      objectPosition: 'center 32%', // protect face, eyes, and hood
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '330px',
    },
  },
  {
    id: 'scene-05',
    index: 4,
    chapterNumber: '05',
    folderName: 'Damyaan_awakening_in_chamber',
    frameCount: 240,
    title: 'THE CHAMBER REMEMBERS',
    subtitle: 'POWER HAS RETURNED.',
    storyDetail: 'Dormant magic ignites across the serpentine altars.',
    eyebrow: 'CHAPTER V · RESURGENCE',
    colorAccent: '#10b981',
    vignetteStrength: 0.7,
    scrollWeight: 1.4,
    desktop: {
      objectPosition: 'center 42%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '560px',
    },
    mobile: {
      objectPosition: 'center 38%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '310px',
    },
  },
  {
    id: 'scene-06',
    index: 5,
    chapterNumber: '06',
    folderName: 'Archaeological_discovery_in_ruin treasure',
    frameCount: 300,
    title: 'THE FORBIDDEN RUINS',
    subtitle: 'Long before the surface world forgot this place, something was waiting beneath it.',
    eyebrow: 'CHAPTER VI · THE HOARD',
    colorAccent: '#d4af37', // aged gold accent
    vignetteStrength: 0.75,
    scrollWeight: 1.3,
    desktop: {
      objectPosition: 'center 50%',
      scale: 1.0,
      textPosition: 'bottom-left',
      textMaxWidth: '540px',
    },
    mobile: {
      objectPosition: 'center 48%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '310px',
    },
  },
  {
    id: 'scene-07',
    index: 6,
    chapterNumber: '07',
    folderName: 'Chamber_awakening_with_green_energy',
    frameCount: 300,
    title: 'YOU HAVE ENTERED THE LAIR.',
    subtitle: 'DAMYAAN AWAKENS.',
    storyDetail: 'The venom runs eternal. You are now part of the domain.',
    eyebrow: 'CHAPTER VII · THE AWAKENING',
    cta: 'ENTER AGAIN',
    isClimax: true,
    colorAccent: '#22c55e',
    vignetteStrength: 0.7,
    scrollWeight: 1.6, // climax scroll space
    desktop: {
      objectPosition: 'center 45%',
      scale: 1.02,
      textPosition: 'bottom-center',
      textMaxWidth: '620px',
    },
    mobile: {
      objectPosition: 'center 40%',
      scale: 1.0,
      textPosition: 'bottom-center',
      textMaxWidth: '330px',
    },
  },
];
